events { }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    types {
        application/wasm wasm;
    }

    server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(dll|wasm)$ {
            add_header Cache-Control "no-cache";
            types {
                application/octet-stream dll;
                application/wasm wasm;
            }
        }
    }
}
